#!/bin/bash
echo "DBHost \"${DB_HOST}\"" > /opt/hlxce/hlstats.conf
echo "DBUsername \"${DB_USERNAME}\"" >> /opt/hlxce/hlstats.conf
echo "DBPassword \"${DB_PASSWORD}\"" >> /opt/hlxce/hlstats.conf
echo "DBName \"${DB_NAME}\"" >> /opt/hlxce/hlstats.conf
echo "BindIP \"${LISTEN_IP}\"" >> /opt/hlxce/hlstats.conf
echo "Port ${LISTEN_PORT}" >> /opt/hlxce/hlstats.conf
echo "CpanelHack 0">> /opt/hlxce/hlstats.conf
echo "EventQueueSize ${EVENT_QUEUE}" >> /opt/hlxce/hlstats.conf
echo "DebugLevel 1" >> /opt/hlxce/hlstats.conf

crontab /opt/hlxce/daemon.txt
crond -l 2

exec "$@"
